[package]
name = "chain_lib"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.11.2"
openzeppelin = "1.0.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.40.0" }
assert_macros = "2.11.2"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
